schema_version = "1.0.0"

id = "sakura_poselib"
version = "1.4.2"
name = "Sakura Poselib"
tagline = "Yet another Pose Library with handful features"
maintainer = "Kafuji Sato"
# Supported types: "add-on", "theme"
type = "add-on"

# Optional link to documentation, support, source files, etc
website = "https://github.com/kafuji/Sakura_Poselib"

# Optional list defined by Blender and server, see:
# https://docs.blender.org/manual/en/dev/extensions/tags.html
tags = ["Animation"]

blender_version_min = "4.2.0"
# blender_version_max = "5.1.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

# Optional: required by some licenses.
copyright = [
   "2023-2024 Kafuji Sato",
]

[permissions] 
files = "Save/Load Poselib data as Json or CSV"
